urls.py
from django.conf.urls import url

from .views import read, messaging

urlpatterns = [
    url(r'^read/message/(?P<message_id>\d+)/$', read, name='read_message'),
    url(r'^$', messaging, name='messaging_home'),
]

models.py
import re

from django.contrib.auth import get_user_model
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.core.mail import send_mass_mail
from django.core.urlresolvers import reverse
from django.db import models, connection
from django.utils import timezone
from django.template import loader
from django.utils.encoding import python_2_unicode_compatible

from mptt.models import MPTTModel, TreeForeignKey

from vle.models import CourseMember, GroupMember, expand_user_group_course_ids_to_user_ids


date_format = '%d/%m/%Y %H:%M:%S'
delimiter = '::'


@python_2_unicode_compatible
class Message(MPTTModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    is_notification = models.BooleanField(default=False)
    url = models.URLField(blank=True)
    subject = models.CharField(max_length=200, blank=True)
    body = models.TextField(blank=True)
    sent = models.DateTimeField(auto_now_add=True, db_index=True)
    target_all = models.BooleanField(default=False, db_index=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

    def __str__(self):
        t = (
            u'Notification' if self.is_notification else u'Message',
            self.subject,
            self.sent.strftime(date_format),
        )
        return u'(%s) subject "%s" sent @ %s' % t

    def get_sent_display(self):
        """
        if it's today, return the time
        otherwise, return the date
        """
        fmt = '%H:%M' if self.sent.date() == timezone.now().date() else '%a %d/%m'
        return timezone.localtime(self.sent).strftime(fmt)

    @classmethod
    def send_message(cls, sender, recipients, subject, body, parent=None, send_email=False):
        # create one Message
        message = Message.objects.create(user=sender, subject=subject, body=body, parent=parent)

        # TODO create one MessageAttachment per attachment

        # get a list of ids of each user, course and group recipient and create message items based on those
        f = lambda _type: [r.get('id') for r in recipients if r.get('id', '') and r.get('type', '') == _type]
        user_ids = f(u'u')
        group_ids = f(u'g')
        course_ids = f(u'c')
        all_user_ids = expand_user_group_course_ids_to_user_ids(delimiter, user_ids, group_ids, course_ids)
        MessageItem.create_message_items(message, all_user_ids)

        # email the message thread
        if send_email:
            Message.email_thread(message, all_user_ids)

        # create one 'source' MessageItem for the sender if the sender wasn't a recipient
        if not MessageItem.objects.filter(message=message, user=sender).exists():
            MessageItem.objects.create(user=sender, message=message, source=True, read=timezone.now())

        # create exactly one MessageTargetUser per user recipient
        for _id in user_ids:
            MessageTargetUser.objects.create(user=get_user_model().objects.get(pk=_id), message=message)

        # create exactly one MessageTargetCourse per course recipient
        for _id in course_ids:
            MessageTargetCourse.objects.create(vle_course_id=_id, message=message)

        # create exactly one MessageTargetGroup per group recipient
        for _id in map(lambda p: p.split(delimiter), group_ids):
            MessageTargetGroup.objects.create(vle_course_id=_id[0], vle_group_id=_id[1], message=message)

        # return the newly created message
        return message

    @classmethod
    def send_message_all(cls, sender, subject, body, parent=None):
        # create one Message
        message = Message.objects.create(user=sender, subject=subject, body=body, target_all=True, parent=parent)

        # TODO create one MessageAttachment per attachment

        # create exactly one MessageItem per user (except (other) super users)
        for u in get_user_model().objects.filter(is_superuser=False):
            MessageItem.objects.create(user=u, message=message)

        # return the newly created message
        return message

    @classmethod
    def email_thread(cls, message, all_user_ids):
        # use mptt to get ancestors of the message (including the message itself)
        messages = message.get_ancestors(ascending=True, include_self=True)

        # build email body
        c = {
            'wwwroot': settings.WWWROOT,
            'messages': messages,
            'link': reverse('read_message', args=(message.id,))
        }
        subject = ''.join(loader.render_to_string('messaging/email/subject.txt', c).splitlines())
        email_body = loader.render_to_string('messaging/email/body.txt', c)

        # send mass mail
        emails = get_user_model().objects.filter(pk__in=all_user_ids).values_list('email', flat=True)
        l = [(subject, email_body, None, [email]) for email in emails]
        send_mass_mail(tuple(l), fail_silently=True)

    @classmethod
    def send_notification(cls, usernames, url, subject, body):
        # create one notification
        notification = Message.objects.create(is_notification=True, url=url, subject=subject, body=body)

        # send a MessageItem to each user
        for username in usernames:
            try:
                user = get_user_model().objects.get(username=username)
                MessageItem.objects.get_or_create(user=user, message=notification)
            except get_user_model().DoesNotExist:
                pass

        # return the newly created notification
        return notification


@python_2_unicode_compatible
class MessageAttachment(models.Model):
    message = models.ForeignKey(Message)
    file = models.FileField(upload_to='%Y/%m/%d', storage=FileSystemStorage(location=settings.MESSAGE_ATTACHMENT_ROOT))

    def __str__(self):
        t = (
            self.message.subject,
            self.file,
        )
        return u'subject "%s" attachment "%s"' % t


@python_2_unicode_compatible
class MessageItem(models.Model):
    message = models.ForeignKey(Message)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    source = models.BooleanField(default=False)
    read = models.DateTimeField(null=True, blank=True, db_index=True)
    deleted = models.DateTimeField(null=True, blank=True, db_index=True)

    def get_thread(self):
        """
        Gets a thread (a list of undeleted message items) given by self.message.
        To do this, we select all undeleted message items (belonging to self.user) that have a message.tree_id
        equal to self.message.tree_id.
        The ordering is newest first, like OWA (as opposed to gmail, which orders by oldest first).
        """

        # query
        sql = """
            FROM messaging_messageitem mi1
            INNER JOIN messaging_message m1
                ON m1.id = mi1.message_id
                AND m1.is_notification = %s
            INNER JOIN messaging_message m2
                ON m2.tree_id = m1.tree_id
                AND m2.is_notification = %s
            INNER JOIN messaging_messageitem mi2
                ON mi2.message_id = m2.id
                AND mi2.user_id = mi1.user_id
                AND mi2.deleted IS NULL
            WHERE mi1.id = %s
        """

        # get items
        params = [False, False, self.id]
        items = MessageItem.objects.raw(''.join(['SELECT mi2.*', sql, ' ORDER BY m2.sent DESC']), params)

        # get count
        cursor = connection.cursor()
        cursor.execute(''.join(['SELECT COUNT(mi2.id)', sql]), params)
        count = cursor.fetchone()

        # return a pair
        return items, count[0]

    @classmethod
    def mark_all_read(cls, message_items):
        """
        marks each of the given message items as read
        """
        unread = filter(lambda mi: mi.read is None, message_items)
        n = timezone.now()
        for message_item in unread:
            message_item.read = n
            message_item.save()

    @classmethod
    def mark_all_deleted(cls, message_items):
        """
        marks each of the given message items as deleted
        """
        unread = filter(lambda mi: mi.deleted is None, message_items)
        n = timezone.now()
        for message_item in unread:
            message_item.deleted = n
            message_item.save()

    @classmethod
    def create_message_items(cls, message, all_user_ids):
        """
        create exactly one MessageItem per user
        """
        for _id in all_user_ids:
            MessageItem.objects.create(user=get_user_model().objects.get(pk=_id), message=message)

    @classmethod
    def get_notifications(cls, user):
        """
        gets the message items which comprise the given user's notifications
        """
        mi = MessageItem.objects.filter(message__is_notification=True, user=user, deleted=None).order_by('-message__sent')
        return mi, mi.count()

    @classmethod
    def get_inbox(cls, user, sort_field='date', sort_dir='desc'):
        """
        gets the message items which comprise the given user's inbox
        main query: select all the message items that should appear in the given user's inbox
        sub query: select the most recently sent message (that was sent to the given user) within the thread
        """

        # query
        sql = """
            FROM messaging_messageitem mi
            INNER JOIN messaging_message m
                ON mi.message_id = m.id
            INNER JOIN auth_user u
                ON u.id = m.user_id
            WHERE mi.user_id = %s
                AND m.is_notification = %s
                AND m.id = (
                    SELECT m1.id
                    FROM messaging_message m1
                    INNER JOIN messaging_messageitem mi1
                        ON mi1.message_id = m1.id
                    WHERE mi1.user_id = mi.user_id
                        AND m1.is_notification = %s
                        AND m1.tree_id = m.tree_id
                        AND mi1.deleted IS NULL

templates/partials/route/composeMessage.html
{% load i18n %}

<div id="id_compose_message">

    <h2 ng-if="newMessage">{% trans 'New message' %}</h2>
    <h2 ng-if="replyTo">{% trans 'Replying to' %}&nbsp;{% verbatim %}{{ replyTo }}{% endverbatim %}</h2>

    {# begin alerts #}
    <alerts messages="messages"></alerts>
    {# end alerts #}

    {# begin buttons #}
    <div id="id_buttons">
        <a href="#/" class="btn btn-default" ng-if="!msg.miid">
            <span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;{% trans 'Back to inbox' %}
        </a>
        <a href="#/read/{% verbatim %}{{ msg.miid }}{% endverbatim %}" class="btn btn-default" ng-if="msg.miid">
            <span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;{% trans 'Back to conversation' %}
        </a>
    </div>
    {# end buttons #}

    {# begin form #}
    <form class="form-horizontal" role="form">

        {# begin send to #}
        <div class="form-group">
            <label for="id_send_to" class="col-sm-2 control-label">{% trans 'To' %}</label>
            <div class="col-sm-10">
                <input type="text"
                       class="form-control"
                       id="id_send_to"
                       placeholder="{% trans 'Search for a recipient' %}"
                       ng-trim
                       ng-model="sendTo"
                       ng-keyup="sendToKeyUp()"
                       ng-disabled="msg.targetAll"/>
                <div id="id_send_to_choices" class="list-group" ng-if="sendToChoices.length > 0">
                    <a href="javascript:;" class="list-group-item" ng-repeat="choice in sendToChoices" ng-click="addRecipient(choice)">
                        <span>{% verbatim %}{{ choice.name }}{% endverbatim %}</span>
                    </a>
                </div>
                <span class="help-block" ng-show="!searching && sendToChoices && pageCount > 1">
                    <ul class="pagination pagination-sm" style="margin: 0;">
                        <li ng-class="prevPageDisabled() ? 'disabled' : ''">
                            <a href="javascript:;" ng-click="prevPage()">&laquo;</a>
                        </li>
                        <li ng-class="pageDisabled(page - 1) ? 'active' : ''" ng-repeat="page in pages">
                            <a href="javascript:;" ng-click="gotoPage(page - 1)">{% verbatim %}{{ page }}{% endverbatim %}</a>
                        </li>
                        <li ng-class="nextPageDisabled() ? 'disabled' : ''">
                            <a href="javascript:;" ng-click="nextPage()">&raquo;</a>
                        </li>
                    </ul>
                </span>
            </div>
        </div>
        {# end send to #}

        {# begin list of recipients #}
        <div class="form-group" ng-if="msg.recipients.length > 0">
            <label class="col-sm-2 control-label">{% trans 'Recipients' %}</label>
            <div class="col-sm-10">
                <span ng-repeat="recipient in msg.recipients">
                    <button type="button" class="btn btn-default recipient" ng-click="removeRecipient(recipient)" ng-disabled="isSender(recipient)">
                        {% verbatim %}{{ recipient.name }}{% endverbatim %}&nbsp;<span class="glyphicon glyphicon-remove" ng-if="!isSender(recipient)"></span>
                    </button>
                </span>
            </div>
        </div>
        {# end list of recipients #}

        {# begin target all #}
        <div class="form-group" ng-if="isSuperUser">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" ng-model="msg.targetAll" ng-change="targetAllChanged()"/>&nbsp;{% trans 'Send to everyone' %}
                    </label>
                </div>
            </div>
        </div>
        {# end target all #}

        {# begin subject #}
        <div class="form-group">
            <label for="id_subject" class="col-sm-2 control-label">{% trans 'Subject' %}</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="id_subject" placeholder="{% trans 'Subject' %}" ng-trim ng-model="msg.subject"/>
            </div>
        </div>
        {# end subject #}

        {# begin body #}
        <div class="form-group">
            <label for="id_body" class="col-sm-2 control-label">{% trans 'Body' %}</label>
            <div class="col-sm-10">
                <blockquote ng-if="replyBody">
                    <p ng-bind-html="replyBody"></p>
                </blockquote>
                <textarea class="form-control" id="id_body" placeholder="{% trans 'Body' %}" rows="10" ng-trim ng-model="msg.body"/>
            </div>
        </div>
        {# end body #}

        {# begin buttons #}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <a href="#/" ng-if="!msg.miid">{% trans 'Cancel' %}&nbsp;</a>
                <a href="#/read/{% verbatim %}{{ msg.miid }}{% endverbatim %}" ng-if="msg.miid">{% trans 'Cancel' %}&nbsp;</a>
                <button type="button"
                        class="btn btn-default"
                        ng-disabled="!((msg.recipients.length > 0 || msg.targetAll) && (msg.subject.length > 0 || msg.body.length > 0))"
                        ng-click="sendMessage()">{% trans 'Send' %}
                </button>
            </div>
        </div>
        {# end buttons #}

    </form>
    {# end form #}

</div>

templates/partials/route/listMessages.html
{% load i18n %}

<div id="id_list_messages">

    <h2>{% trans 'Your inbox' %}</h2>

    {# begin alerts #}
    <alerts messages="messages"></alerts>
    {# end alerts #}

    {# begin buttons #}
    <div id="id_buttons">
        <a href="#/compose" class="btn btn-default"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp;{% trans 'New message' %}</a>
        <div class="pull-right">
            <button type="button" class="btn btn-default" ng-click="setSort('sender')">
                <span ng-class="{'glyphicon': sort.sender, 'glyphicon-arrow-up': sort.senderAsc, 'glyphicon-arrow-down': sort.senderDesc}"></span>&nbsp;{% trans 'Sender' %}
            </button>
            <button type="button" class="btn btn-default" ng-click="setSort('date')">
                <span ng-class="{'glyphicon': sort.date, 'glyphicon-arrow-up': sort.dateAsc, 'glyphicon-arrow-down': sort.dateDesc}"></span>&nbsp;{% trans 'Date' %}
            </button>
        </div>
    </div>
    {# end buttons #}

    {# begin list of inbox messages #}
    <div>
        <div class="list-group">
            {% verbatim %}
                <a ng-repeat="email in inbox" ng-href="#/read/{{ email.id }}" class="list-group-item">
                    <span class="badge">{{ email.sent }}</span>
                    <h4 class="list-group-item-heading">
                        <span ng-if="showMessageItemIds">{{ email.id }}</span>
                        <span ng-if="email.unread == 0">{{ email.sender }}</span>
                        <strong ng-if="email.unread > 0">{{ email.sender }}</strong>
                    </h4>
                    <p class="list-group-item-text" ng-if="email.unread == 0">
                        <span class="glyphicon glyphicon-folder-open"></span>
                        <span ng-if="email.count > 1">&nbsp;&#40;{{ email.count }}&#41;</span>
                        <span ng-if="email.count < 2">&nbsp;</span>
                        <span>{{ email.subject }}</span>
                    </p>
                    <p class="list-group-item-text" ng-if="email.unread > 0">
                        <span class="glyphicon glyphicon-folder-close"></span>
                        <strong ng-if="email.count > 1">&nbsp;&#40;{{ email.count }}&#41;</strong>
                        <strong ng-if="email.count < 2">&nbsp;</strong>
                        <strong>{{ email.subject }}</strong>
                    </p>
                </a>
            {% endverbatim %}
        </div>
    </div>
    {# end list of inbox messages #}

    {# begin pagination #}
    <div id="id_pagination">
        {% verbatim %}
            <pagination per-page="{{ perPage }}"
                        current-page="currentPage"
                        total="total"
                        fetch-page="getPageOfInbox(currentPage)"
                        ng-show="total > perPage">
            </pagination>
        {% endverbatim %}
    </div>
    {# end pagination #}

</div>

templates/partials/route/listNotifications.html
{% load i18n %}

<div class="notifications-container">

    <h2>{% trans 'Your notifications' %}</h2>

    {# begin alerts #}
    <alerts messages="messages"></alerts>
    {# end alerts #}

    {# begin list of notifications #}
    <div>
        <div class="list-group">
            <a ng-repeat="notification in notifications" href="javascript:;" ng-click="clickNotification(notification)" class="list-group-item">
                {% verbatim %}
                    <span class="badge">{{ notification.sent }}</span>
                    <h4 class="list-group-item-heading">
                        <span ng-if="showMessageItemIds">{{ notification.id }}</span>
                        <span ng-if="notification.read">{{ notification.subject }}</span>
                        <strong ng-if="!notification.read">{{ notification.subject }}</strong>
                    </h4>
                {% endverbatim %}
                <div>
                    <div class="pull-left">
                        <p class="list-group-item-text">
                            <span ng-if="notification.read" ng-bind-html="notification.body|raw"></span>
                            <strong ng-if="!notification.read" ng-bind-html="notification.body|raw"></strong>
                        </p>
                    </div>
                    <div class="pull-right">
                        <button type="button" class="btn btn-default btn-sm" ng-click="openModal($event, 'modal_delete_notification', notification.id)">
                            <span class="glyphicon glyphicon-trash"></span>&nbsp;{% trans 'Delete' %}
                        </button>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    {# end list of notifications #}

    {# begin pagination #}
    <div class="notifications-pagination">
        {% verbatim %}
        <pagination per-page="{{ perPage }}"
                    current-page="currentPage"
                    total="total"
                    fetch-page="getPageOfNotifications(currentPage)"
                    ng-show="total > perPage">
        </pagination>
        {% endverbatim %}
    </div>
    {# end pagination #}

    {# begin confirmation modal #}
    <modal-confirm uid="modal_delete_notification"
                   title="{% trans 'Delete notification' %}"
                   body="{% trans 'Are you sure you want to delete this notification?' %}"
                   cancel="cancelDeleteNotification(uid)"
                   confirm="deleteNotification(uid)">
    </modal-confirm>
    {# end confirmation modal #}

</div>

templates/partials/route/readThread.html
{% load i18n %}

<div id="id_read_thread">

    <h2>{% verbatim %}{{ subject }}{% endverbatim %}</h2>

    {# begin alerts #}
    <alerts messages="messages"></alerts>
    {# end alerts #}

    {# begin buttons #}
    <div id="id_buttons">
        <a href="#/" class="btn btn-default"><span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;{% trans 'Back to inbox' %}</a>
    </div>
    {# end buttons #}

    {# begin list of thread messages #}
    <div>
        <ul class="list-group">
            <li ng-repeat="email in thread" class="list-group-item">
                {% verbatim %}
                    <span class="badge">{{ email.sent }}</span>
                    <h4 class="list-group-item-heading">
                        <span ng-if="showMessageItemIds">{{ email.id }}</span>
                        <span ng-if="isRead(email)">{{ email.sender }}</span>
                        <strong ng-if="!isRead(email)">{{ email.sender }}</strong>
                    </h4>
                {% endverbatim %}
                <div>
                    <div class="pull-left">
                        {% verbatim %}
                            <p class="list-group-item-text subject" ng-if="!email.body || (email.subject && email.subject != subject)">
                                <em ng-if="isRead(email)">{{ email.subject }}</em>
                                <em ng-if="!isRead(email)"><strong>{{ email.subject }}</strong></em>
                            </p>
                            <p class="list-group-item-text" ng-bind-html="email.body" ng-if="email.body"></p>
                        {% endverbatim %}
                    </div>
                    <div class="pull-right">
                        <a href="#/reply/{% verbatim %}{{ email.id }}{% endverbatim %}" class="reply btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-share-alt"></span>&nbsp;{% trans 'Reply' %}
                        </a>
                        <button type="button" class="btn btn-default btn-sm" ng-click="openModal('modal_delete_one', email.id)">
                            <span class="glyphicon glyphicon-trash"></span>&nbsp;{% trans 'Delete' %}
                        </button>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </li>
        </ul>
    </div>
    {# end list of thread messages #}

    {# begin buttons #}
    <div>
        <button type="button" class="btn btn-default" ng-if="total" ng-click="openModal('modal_delete_all')">
            <span class="glyphicon glyphicon-trash"></span>&nbsp;{% trans 'Delete all' %}
        </button>
    </div>
    {# end buttons #}

    {# begin confirmation modals #}
        <modal-confirm uid="modal_delete_one"
                       title="{% trans 'Delete message' %}"
                       body="{% trans 'Are you sure you want to delete this message?' %}"
                       cancel="cancelDeleteMessage(uid)"
                       confirm="deleteOne(uid)">
        </modal-confirm>
        <modal-confirm uid="modal_delete_all"
                       title="{% trans 'Delete conversation' %}"
                       body="{% trans 'Are you sure you want to delete this conversation?' %}"
                       cancel="cancelDeleteMessage(uid)"
                       confirm="deleteAll(uid)">
        </modal-confirm>
    {# end confirmation modals #}

</div>